### ISSUE TITLE
How to make drone's location in DefualtLayoutActivity's minimap?

### ISSUE THREAD

**Issue by sihunbaek** [dji-sdk/Mobile-UXSDK-Beta-Android#11]
As you see the Sample code, there are no functions to make drone's location on map. So I tried to make it by putting some codes of google map tutorials to beta sample code(DefaultLayoutActivity more precisely).
What I added the codes are
-------
    private void initFlightController() {

        BaseProduct product = SampleApplication.getProductInstance();
        if (product != null && product.isConnected()) {
            if (product instanceof Aircraft) {
                mFlightController = ((Aircraft) product).getFlightController();
                Log.d(TAG, "mFlightController :"+mFlightController);
                Log.d(TAG, "getAircraftlocaiton :"+mFlightController.getState().getAircraftLocation());

            }
        }

        if (mFlightController != null) {
            mFlightController.setStateCallback(new FlightControllerState.Callback() {

                @Override
                public void onUpdate(FlightControllerState djiFlightControllerCurrentState) {
                    droneLocationLat = djiFlightControllerCurrentState.getAircraftLocation().getLatitude();
                    droneLocationLng = djiFlightControllerCurrentState.getAircraftLocation().getLongitude();
                    Log.d(TAG, "droneLocationLat :"+droneLocationLat+",\""+"droneLocationLng :"+droneLocationLng);
                    Log.d(TAG, "getAircraftlocaiton :"+mFlightController.getState().getAircraftLocation());
                    updateDroneLocation();
                }
            });
        }
    }

    private void updateDroneLocation(){

        DJILatLng pos = new DJILatLng(droneLocationLat, droneLocationLng);
        //Create MarkerOptions object
        final DJIMarkerOptions markerOptions = new DJIMarkerOptions();
        markerOptions.position(pos);
        markerOptions.icon(DJIBitmapDescriptorFactory.fromResource(R.drawable.ic_drone));

        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                if (droneMarker != null) {
                    droneMarker.remove();
                }

                if (checkGpsCoordination(droneLocationLat, droneLocationLng)) {
                    droneMarker = mapWidget.getMap().addMarker(markerOptions);
                }
            }
        });
    }

    public static boolean checkGpsCoordination(double latitude, double longitude) {
        return (latitude > -90 && latitude < 90 && longitude > -180 && longitude < 180) && (latitude != 0f && longitude != 0f);
    }
-----------------------------
and when I press the defaultlayout button with simulator to make drone's location, the app is crushed.
And the main errors say : 
 1.   java.lang.RuntimeException: Unable to resume activity {com.dji.ux.beta.sample/com.dji.ux.beta.sample.DefaultLayoutActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'com.dji.mapkit.core.models.annotations.DJIMarker com.dji.mapkit.core.maps.DJIMap.addMarker(com.dji.mapkit.core.models.annotations.DJIMarkerOptions)' on a null object reference

2. Attempt to invoke interface method 'com.dji.mapkit.core.models.annotations.DJIMarker com.dji.mapkit.core.maps.DJIMap.addMarker(com.dji.mapkit.core.models.annotations.DJIMarkerOptions)' on a null object reference

**Comment by siddutgikar** [comment]
Hi @sihunbaek ! 
The mapwidget is by default programmed to show the aircraft location. If you are not seeing it, we would love to help debug the problem. Please follow the steps below and provide us with any more information accordingly.
Can you see the map tiles load in DefaultLayoutActivity? 

If the Map already loads and the marker does not 
1. Please verify the aircraft is getting a location. This can be verified using your function initFlightController(). Please make sure the logs reflect the co-ordinates.
If the location co-ordinates are coming through as expected then please let us know.

If NO,
1. The DefaultLayout Activity if used as it is, is programmed to use **AMap** Provider. Please make sure you have the  AMap sdk key in **keystrings.xml** file.
2. In case you have modified this to use another provider please make sure the correct sdk key is included in the keystrings.xml file.

The resason you are seeing a crash is because you are adding a marker on a null map object. This may be because the mapwidget is not initialized or has failed to initialize. This can be because of the missing sdk keys. 
When the MapWidget is initialized it provides a callback. The map object will be returned in this callback. 
If `getMap()` method is being used, please make sure the intialization is successful.
For reference, please refer 
1. https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/blob/master/android-uxsdk-beta-sample/src/main/java/com/dji/ux/beta/sample/DefaultLayoutActivity.java **Line 97**
2. https://github.com/dji-sdk/Mobile-UXSDK-Beta-Android/blob/master/android-uxsdk-beta-sample/src/main/java/com/dji/ux/beta/sample/MapWidgetActivity.java **Line 137**
 
Please let us know if you need further help or come across an issue.

**Comment by sihunbaek** [comment]
Now I noticed that the mapwidget is by default programmed to show the aircraft location. So I modified it to original version and just changed the initialization amap to google map.       
mapWidget.initGoogleMap(map -> map.setOnMapClickListener(latLng -> onViewClick(mapWidget)));
And the map tiles load in defaultlayout activity. But aircraft loaction is not appeared. I am using dji assistant2 so that i can make drone's locaiton in my house. But What I think the problem is that the state masseage mostly shows "Aircraft Disconnected" But Sometimes location is appeared with the messasge "Airacraft Controller error" that somethinkg like 
How can I make the better connection with the smart phone and flight controller in a manner of coding or situation?

**Comment by siddutgikar** [comment]
Glad to know that you worked out the map loading.
For the aircraft location loading, try without the DJI Assistant. Your drone should be able to get a GPS fix if you have it close to a window. To verity this, observe the SystemStatusWidget. The message should show "Ready to Go (GPS)". 

For the Aircraft Controller error, I would suggest you to update the firmware of the controller and the aircraft to the latest firmware available. Once that is done, please verify using the DJI GO app the error does not show up.

For easier development setup, you can take a look at the [Android Bridge App](https://github.com/dji-sdk/Android-Bridge-App)
